### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [Nadiafa/prj-rev-bwfs-dasmoto#7]
Satisfactory 👍

You've successfully reproduced the website according to the design mock. You've demonstrated a solid understanding of using HTML to markup your page's content and structure and of using CSS to apply fundamental styles.

Try to make more strategic use of `div` tags, classes and IDs, indentation and whitespace to organize your HTML and CSS and make it easier to read and maintain. Avoid unnecessary repetition and complexity in your CSS by applying shared styles with more general selectors.

**Comment by Nadiafa** [comment]
Thank you for your comments and advice Steve. I do have a couple additional questions on the suggestions, that I hope you don't mind checking? I will send them in their individual issue section.
Thanks!!
